language: node_js
node_js: node
env:
- NODE_ENV=test
services:
- mongod
deploy:
  provider: heroku
  api_key:
    secure: RVJGQxEaylIkpZAP6yd7/1hTlyj+vsLggXUwzvO5B0syz2W8sBlXC76PDhrA3Xzc9XjR6f7favWVWNo5QPknzzoIQOVhy9Qk2KO9mS146122n9S2CCKM62UtmqpSSG5/nggLg3o2RFtFAuC4hvrxTAKjb4ykoZZKUKOH/HMq70eLzrszQ+Avm35lhCwOJZeUQIVy8ZZjOqXS8TsB09URwYwfgrLGP7BBaYcwd7mY5EGbU+cyEcjOF9+9PJE0lJBJ1NxPjhBnhIFbTOZIhbMPeTB6+wcpsscw7keQi2gehOI+dslx/MHl4I/PZPp3pEBKooL3SKjmZNTIUaaue1IAeXFz3W9mxAqzsb8BDbeELjZr5x7x8TUd23TojPSyGn4zQV9SXyZhBtJRSo/qlMDYGc/SK4lVMqANSA3raDk4WQ5jCbiMUAg9P0jBIH1GxmI6xU8PV6pnm5qUQ2kMFxmy8yhazwHYRgKUeJ1iv9mAL5mqjcxjxEG/DqDnOPdCb6jB7QhFbnz2LQn/AaYziwQCmEG6p3tT9YDDCE1mmGDAGNfn5ftcZJc6q3sWQcieJQE/ogFcILhuYha5sGwWcmk4OHYPt6bbxouczTmnMnCTus/P1XIJ8hjqiTL+WVjebc1PDP1PsG5wOBgyDBuYWzyP2eIwfDgsm8wfGbnXuCV9zGs=
  app: julie-noteful-app-v3
  on:
    repo: thinkful-ei19/julie-noteful-app-v3
